# -*- coding: utf-8 -*-
"""UNet_Baseline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zYkdX7gzOY6JWbYmEndD1p3bgwZ9E_jk

Data loader
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import os
import torch
import random
import zipfile
import cv2

from torch.utils.data import Dataset, DataLoader

def unzip(zip_path, target):
  if os.path.exists(zip_path):
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
      zip_ref.extractall(target)
    return target

unzip('/content/drive/MyDrive/UNet_Project/ISIC2018_Task1_Training_GroundTruth.zip', '/content')
unzip('/content/drive/MyDrive/UNet_Project/ISIC2018_Task1_Test_GroundTruth.zip', '/content')
unzip('/content/drive/MyDrive/UNet_Project/ISIC2018_Task1-2_Training_Input.zip', '/content')
unzip('/content/drive/MyDrive/UNet_Project/ISIC2018_Task1-2_Test_Input.zip', '/content')


class Config:
  #load images and paths
  def __init__(self):

    self.train = '/content/ISIC2018_Task1_Training_GroundTruth'
    self.test = '/content/ISIC2018_Task1_Test_GroundTruth'
    self.image_folder_train = '/content/ISIC2018_Task1-2_Training_Input'
    self.image_folder_test = '/content/ISIC2018_Task1-2_Test_Input'
    self.batch_size = 8 #lowered batch size to 8 cause computer was struggling
    self.lr = 0.0001
    self.num_epochs = 10

config = Config()

class LesionSegmentation(Dataset):
    def __init__(self, root_dir, ground_dir, is_train = True):
        self.root_dir = root_dir
        self.ground_dir = ground_dir
        self.is_train = is_train

        self.files = [f for f in os.listdir(root_dir) if f.lower().endswith('.jpg')]
        self.files.sort()

        self.mean = [0.485, 0.456, 0.406]
        self.std = [0.229, 0.224, 0.225]

    def __len__(self):
        return len(self.files)

    def __getitem__(self, idx):
        raw_name = self.files[idx]
        filename = os.path.splitext(raw_name)[0]
        ground_name = filename + '_segmentation.png'
        img_path = os.path.join(self.root_dir, raw_name)
        ground_path = os.path.join(self.ground_dir, ground_name)

        img = cv2.imread(img_path)
        img = cv2.resize(img, (572 , 572), interpolation=cv2.INTER_LINEAR) #resizing to 572, 572 to keep compatible with og unet
        img = img.astype(np.float32) / 255.0

        ground = cv2.imread(ground_path, cv2.IMREAD_GRAYSCALE)
        ground = cv2.resize(ground, (572,572), interpolation=cv2.INTER_NEAREST)

        if self.is_train:
          # randomly rotate and flip to improve results
            nrotate = random.randint(0, 3)
            img = np.rot90(img, nrotate)
            ground = np.rot90(ground, nrotate)
            if random.random() > 0.5:
                img = np.fliplr(img)
                ground = np.fliplr(ground)

            img = img.copy()
            ground = ground.copy()

        for i in range(img.shape[2]):
            img[:, :, i] = (img[:, :, i] - self.mean[i]) / self.std[i]

        img = np.transpose(img, (2, 0, 1))
        #convert to tensor
        img_tensor = torch.from_numpy(img.copy()).float()
        ground_tensor = torch.from_numpy(ground.copy()).float()
        ground_tensor = (ground_tensor > 0.5).float()


        return img_tensor, ground_tensor

train_dataset = LesionSegmentation(config.image_folder_train, config.train, is_train = True)
test_dataset = LesionSegmentation(config.image_folder_test, config.test, is_train = False)
print('total training samples', len(train_dataset))
print('total testing samples', len(test_dataset))

train_loader = DataLoader(train_dataset, batch_size = config.batch_size, shuffle = True, num_workers=2)
test_loader = DataLoader(test_dataset, batch_size = config.batch_size, num_workers=2)

"""
*   UNet Baseline

*   Github:https://github.com/spctr01/UNet/blob/master/Unet.py


*   Changed dual_conv(1, 64) -> dual_conv(3, 64) to handle rgb instead of just greyscale


*   Changed image = torch.rand((1, 1, 572, 572)) ->image = torch.rand((1, 3, 572, 572))




"""

import torch
import torch.nn as nn


#double 3x3 convolution
def dual_conv(in_channel, out_channel):
    conv = nn.Sequential(
        nn.Conv2d(in_channel, out_channel, kernel_size=3),
        nn.ReLU(inplace= True),
        nn.Conv2d(out_channel, out_channel, kernel_size=3),
        nn.ReLU(inplace= True),
    )
    return conv


# crop the image(tensor) to equal size
# as shown in architecture image , half left side image is concated with right side image
def crop_tensor(target_tensor, tensor):
    target_size = target_tensor.size()[2]
    tensor_size = tensor.size()[2]
    delta = tensor_size - target_size
    delta = delta // 2

    return tensor[:, :, delta:tensor_size- delta, delta:tensor_size-delta]

class Unet(nn.Module):
    def __init__(self):
        super(Unet, self).__init__()

        # Left side (contracting path)
        self.dwn_conv1 = dual_conv(3, 64)
        self.dwn_conv2 = dual_conv(64, 128)
        self.dwn_conv3 = dual_conv(128, 256)
        self.dwn_conv4 = dual_conv(256, 512)
        self.dwn_conv5 = dual_conv(512, 1024)
        self.maxpool = nn.MaxPool2d(kernel_size=2, stride=2)

        #Right side  (expnsion path)
        #transpose convolution is used showna as green arrow in architecture image
        self.trans1 = nn.ConvTranspose2d(1024,512, kernel_size=2, stride= 2)
        self.up_conv1 = dual_conv(1024,512)
        self.trans2 = nn.ConvTranspose2d(512,256, kernel_size=2, stride= 2)
        self.up_conv2 = dual_conv(512,256)
        self.trans3 = nn.ConvTranspose2d(256, 128, kernel_size=2, stride= 2)
        self.up_conv3 = dual_conv(256,128)
        self.trans4 = nn.ConvTranspose2d(128,64, kernel_size=2, stride= 2)
        self.up_conv4 = dual_conv(128,64)

        #output layer
        self.out = nn.Conv2d(64, 2, kernel_size=1)

    def forward(self, image):

        #forward pass for Left side
        x1 = self.dwn_conv1(image)
        x2 = self.maxpool(x1)
        x3 = self.dwn_conv2(x2)
        x4 = self.maxpool(x3)
        x5 = self.dwn_conv3(x4)
        x6 = self.maxpool(x5)
        x7 = self.dwn_conv4(x6)
        x8 = self.maxpool(x7)
        x9 = self.dwn_conv5(x8)


        #forward pass for Right side
        x = self.trans1(x9)
        y = crop_tensor(x, x7)
        x = self.up_conv1(torch.cat([x,y], 1))

        x = self.trans2(x)
        y = crop_tensor(x, x5)
        x = self.up_conv2(torch.cat([x,y], 1))

        x = self.trans3(x)
        y = crop_tensor(x, x3)
        x = self.up_conv3(torch.cat([x,y], 1))

        x = self.trans4(x)
        y = crop_tensor(x, x1)
        x = self.up_conv4(torch.cat([x,y], 1))

        x = self.out(x)

        return x

if __name__ == '__main__':
    image = torch.rand((1, 3, 572, 572))
    model = Unet()
    model(image)

"""Main"""

import time
import numpy as np
import matplotlib.pyplot as plt
import torch.nn as nn


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = Unet().to(device)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.AdamW(model.parameters(), lr= config.lr, weight_decay= 0.005)


train_loss_list = []

#Training loop
for epoch in range(1, config.num_epochs + 1):
  model.train()
  running_loss = 0.0
  time1 = time.time()

  for images, ground in train_loader:
    images = images.float().to(device)
    ground = ground.to(device)

    # Add channel dimension to ground truth for consistency with model output
    if len(ground.shape) == 3:
      ground = ground.unsqueeze(1)

    outputs = model(images)

    #squeeze and crop ground truth for valid output
    processed_ground = crop_tensor(outputs, ground).squeeze(1).long()
    loss = criterion(outputs, processed_ground)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    running_loss += loss.item()

  avg_loss = running_loss / len(train_loader)
  train_loss_list.append(avg_loss)

  time2 = time.time()
  print('-----------------------------------')
  print('Epoch {}, total time {:.2f}'.format(epoch, time2 - time1))
  print('train_loss average', avg_loss)


model.eval()
iouScores = []
diceScores = []

#Test loop
with torch.no_grad():
  for images, ground in test_loader:
      images = images.float().to(device)
      ground = ground.float().to(device)

      if len(ground.shape) == 3:
        ground = ground.unsqueeze(1)


      outputs = model(images)
      cropped_ground = crop_tensor(outputs, ground) # must crop ground so that it matches model output size
      cropped_ground = cropped_ground.squeeze(1)

      prob = torch.sigmoid(outputs)
      predict = torch.argmax(outputs, dim =1)

      #Calculate IoU -> intersection area/ union area
      intersect = (predict * cropped_ground).sum(dim=(-2, -1))
      union = (predict + cropped_ground).sum(dim=(-2, -1)) - intersect

      iou = torch.nan_to_num(intersect / union, nan=1.0)
      dice = torch.nan_to_num((2 * intersect) / (predict.sum(dim=(-2,-1)) + cropped_ground.sum(dim=(-2,-1))), nan=1.0)

      iouScores.extend(iou.cpu().numpy())
      diceScores.extend(dice.cpu().numpy())




print(f'Average test IoU: {np.mean(iouScores):.4f}')
print(f'Average Dice: {np.mean(diceScores):.4f}')

show_img = 3
fig, axes = plt.subplots(show_img, 3, figsize= (15, 5 * show_img))

for i in range(show_img):

  img_display = images.cpu()[i].permute(1, 2, 0).numpy()
  img_display = np.clip(img_display * [0.229, 0.224, 0.225] + [0.485, 0.456, 0.406], 0, 1)

  axes[i, 0].imshow(img_display)
  axes[i, 0].set_title("Image")

  axes[i, 1].imshow(predict.cpu()[i].squeeze())
  axes[i, 1].set_title("Prediction")

  axes[i, 2].imshow(ground.cpu()[i].squeeze())
  axes[i, 2].set_title("Ground Truth")

plt.figure(figsize=(8, 5))
plt.plot(train_loss_list, marker='o')
plt.title("Training loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.grid(True)
plt.show()

plt.tight_layout()
plt.show()